//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAAL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAAL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [COMMENT]
        ///	[NAME]MATSUSHITA
        ///
        ///[COMMANDS]
        ///[POWER]00 A4 00 A4 00 28 00 7B 00 28 00 28 00 28 00 28 00 28 00 7B 00 28 00 28 00 28 00 7B 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 7B 00 28 00 28 00 28 00 7B 00 28 00 7B 00 28 00 28 00 28 00 7B 00 28 00 28 00 28 00 7B 00 28 00 7B 00 28 00 7B 00 28 00 7B 00 28 00 7B 00 28 00 28 FF FF
        ///[CHUP]00 A4 00 A4 00 28 00 7B 00 28 00 28 00 28 00 28 00 28 00 7B 00 28 00 28 00 28 00 7B 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 28 00 7B 00 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_MATSUSHITA {
            get {
                return ResourceManager.GetString("IRTOY_MATSUSHITA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [COMMENT]
        ///	[NAME]NEC
        ///
        ///[COMMANDS]
        ///[POWER]01 A6 00 DA 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 1C 00 1C 00 52 00 1C 00 52 FF FF
        ///[CHUP]01 A6 00 DA 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_NEC {
            get {
                return ResourceManager.GetString("IRTOY_NEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [COMMENT]
        ///	[NAME]NEC_INDIA
        ///
        ///[COMMANDS]
        ///[POWER]01 A6 00 DA 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A FF FF
        ///[CHUP]01 A6 00 DA 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_NEC_INDIA {
            get {
                return ResourceManager.GetString("IRTOY_NEC_INDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [COMMENT]
        ///	[NAME]NEC_THAI
        ///
        ///[COMMANDS]
        ///[POWER]01 A6 00 DA 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 52 00 1C 00 1C 00 1C 00 52 00 1C 00 52 FF FF
        ///[CHUP]01 A6 00 DA 00 1C 00 1C 00 1C 00 1C 00 1C 00 52 00 1C  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_NEC_THAI {
            get {
                return ResourceManager.GetString("IRTOY_NEC_THAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [REMOTE]
        ///	[NAME]PHILIPS_RC5
        ///
        ///[COMMANDS]
        ///[POWER]00 2A 00 2A 00 53 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 53 00 2A 00 2A 00 53 00 2A 00 2A 00 2A FF FF
        ///[SLEEP]00 2A 00 2A 00 53 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 53 00 53 00 2A 00 2A 00 53 00 2A 00 2A 00 53 00 2A FF FF
        ///[FORMAT]00 53 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 53 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 2A 00 53 00 2A FF FF
        ///[OPTIONS]00  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_PHILIPS_RC5 {
            get {
                return ResourceManager.GetString("IRTOY_PHILIPS_RC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [COMMENT]
        ///	[NAME]PHILIPS_RC6
        ///
        ///[COMMANDS]
        ///[POWER]00 7D 00 2A 00 15 00 2A 00 15 00 15 00 15 00 15 00 3E 00 3E 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 2A 00 15 00 15 00 2A 00 15 00 15 00 15 FF FF            
        ///[CHUP]00 7D 00 2A 00 15 00 2A 00 15 00 15 00 15 00 15 00 3E 00 3E 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 15 00 2A 00 2A 00 15 00 15 00 15 00 15 00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_PHILIPS_RC6 {
            get {
                return ResourceManager.GetString("IRTOY_PHILIPS_RC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [COMMENT]
        ///	[NAME]SANYO
        ///
        ///[COMMANDS]
        ///[POWER]01 A6 00 DA 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 1C 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00 1A 00 52 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 1C 00 1A 00 52 00 1A 00 52 00 1A 00 52 00 1A FF FF
        ///[CHUP]01 A6 00 DA 00 1A 00 1C 00 1A 00 1C 00 1A 00 1C 00  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IRTOY_SANYO {
            get {
                return ResourceManager.GetString("IRTOY_SANYO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scan_image {
            get {
                object obj = ResourceManager.GetObject("scan_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
